# permissions for end users to view clustervectoraggregators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vector-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustervectoraggregator-viewer-role
rules:
- apiGroups:
  - observability.kaasops.io
  resources:
  - clustervectoraggregators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.kaasops.io
  resources:
  - clustervectoraggregators/status
  verbs:
  - get
