apiVersion: observability.kaasops.io/v1alpha1
kind: VectorAggregator
metadata:
  labels:
    app.kubernetes.io/name: vector-operator
    app.kubernetes.io/managed-by: kustomize
  name: vectoraggregator-sample
spec:
  image: "timberio/vector:0.28.1-debian"
  internalMetrics: false
  replicas: 1
  api:
    enabled: true
    healthcheck: true
  configCheck:
    disabled: true
  resources:
    limits:
      cpu: 500m
      memory: 800Mi
    requests:
      cpu: 10m
      memory: 20Mi
